services:
  xash3d:
    image: yohimik/hl-web-server-metpamx:latest
    build:
      context: ../../
      dockerfile: ./docker/hl-web-server-metpamx/Dockerfile
      tags:
        - yohimik/hl-web-server-metpamx:latest
        - yohimik/hl-web-server-metpamx:${TAG}
    restart: always
    platform: linux/386
    environment:
      PORT: 27018
    volumes:
      - "./valve.zip:/xashds/public/valve.zip"
    ports:
      - "27016:27016"
      - "27018:27018"
      - "27018:27018/udp"